logo = """
  _______ _            ____            _           _                          ____        _     
 |__   __| |          |  _ \          (_)         | |                        / __ \      (_)    
    | |  | |__   ___  | |_) |_ __ __ _ _ _ __  ___| |_ ___  _ __ _ __ ___   | |  | |_   _ _ ____
    | |  | '_ \ / _ \ |  _ <| '__/ _` | | '_ \/ __| __/ _ \| '__| '_ ` _ \  | |  | | | | | |_  /
    | |  | | | |  __/ | |_) | | | (_| | | | | \__ \ || (_) | |  | | | | | | | |__| | |_| | |/ / 
    |_|  |_| |_|\___| |____/|_|  \__,_|_|_| |_|___/\__\___/|_|  |_| |_| |_|  \___\_\\__,_|_/___|
    """

question_data_mcq = [
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which best selling toy of 1983 caused hysteria, resulting in riots breaking out in stores?",
     "correct_answer": "Cabbage Patch Kids",
     "incorrect_answers": ["Transformers", "Care Bears", "Rubik's Cube"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the largest organ of the human body?", "correct_answer": "Skin",
     "incorrect_answers": ["Heart", "large Intestine", "Liver"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What alcoholic drink is made from molasses?", "correct_answer": "Rum",
     "incorrect_answers": ["Gin", "Vodka", "Whisky"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which one of the following rhythm games was made by Harmonix?", "correct_answer": "Rock Band",
     "incorrect_answers": ["Meat Beat Mania", "Guitar Hero Live", "Dance Dance Revolution"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "How many colors are there in a rainbow?", "correct_answer": "7",
     "incorrect_answers": ["8", "9", "10"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is on display in the Madame Tussaud&#039;s museum in London?",
     "correct_answer": "Wax sculptures",
     "incorrect_answers": ["Designer clothing", "Unreleased film reels",
                           "Vintage cars"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What was the nickname given to the Hughes H-4 Hercules, a heavy transport flying boat which achieved flight in 1947?",
     "correct_answer": "Spruce Goose", "incorrect_answers": ["Noah's Ark", "Fat Man", "Trojan Horse"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which American-owned brewery led the country in sales by volume in 2015?",
     "correct_answer": "D. G. Yuengling and Son, Inc",
     "incorrect_answers": ["Anheuser Busch", "Boston Beer Company", "Miller Coors"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What do the letters of the fast food chain KFC stand for?",
     "correct_answer": "Kentucky Fried Chicken",
     "incorrect_answers": ["Kentucky Fresh Cheese", "Kibbled Freaky Cow", "Kiwi Food Cut"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following presidents is not on Mount Rushmore?", "correct_answer": "John F. Kennedy",
     "incorrect_answers": ["Theodore Roosevelt", "Abraham Lincoln", "Thomas Jefferson"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the Zodiac symbol for Gemini?", "correct_answer": "Twins",
     "incorrect_answers": ["Fish", "Scales", "Maiden"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What are Panama hats made out of?", "correct_answer": "Straw",
     "incorrect_answers": ["Silk", "Hemp", "Flax"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Who is the author of Jurrasic Park?", "correct_answer": "Michael Crichton",
     "incorrect_answers": ["Peter Benchley", "Chuck Paluhniuk", "Irvine Welsh"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Who is the youngest person to recieve a Nobel Prize?", "correct_answer": "Malala Yousafzai",
     "incorrect_answers": ["Lawrence Bragg", "Werner Heisenberg", "Yasser Arafat"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "The drug cartel run by Pablo Escobar originated in which South American city?",
     "correct_answer": "Medell&iacute;n", "incorrect_answers": ["Bogot&aacute;", "Quito", "Cali"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following blood component forms a plug at the site of injuries?",
     "correct_answer": "Platelets", "incorrect_answers": ["Red blood cells", "White blood cells", "Blood plasma"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which country has the union jack in its flag?", "correct_answer": "New Zealand",
     "incorrect_answers": ["South Africa", "Canada", "Hong Kong"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What airline was the owner of the plane that crashed off the coast of Nova Scotia in 1998?",
     "correct_answer": "Swiss Air", "incorrect_answers": ["Air France", "British Airways", "TWA"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What kind of aircraft was developed by Igor Sikorsky in the United States in 1942?",
     "correct_answer": "Helicopter", "incorrect_answers": ["Stealth Blimp", "Jet", "Space Capsule"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Who invented the first ever chocolate bar, in 1847?", "correct_answer": "Joseph Fry",
     "incorrect_answers": ["Andrew Johnson", "John Cadbury", "John Tyler"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What&#039;s the name of the main protagonist in the &quot;Legend of Zelda&quot; franchise?",
     "correct_answer": "Link", "incorrect_answers": ["Mario", "Zelda", "Pit"]},
    {"category": "Entertainment: Comics", "type": "multiple", "difficulty": "easy", "question": "Who is Batman?",
     "correct_answer": "Bruce Wayne", "incorrect_answers": ["Clark Kent", "Barry Allen", "Tony Stark"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In which series of games do you collect souls to empower you and buy weaponry and armor with?",
     "correct_answer": "Souls ", "incorrect_answers": ["Final Fantasy ", "Monster Hunter", "The Legend of Zelda"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "The K\u0101k\u0101p\u014d is a large, flightless, nocturnal parrot native to which country?",
     "correct_answer": "New Zealand", "incorrect_answers": ["South Africa", "Australia", "Madagascar"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "Which country does Austria not border?", "correct_answer": "France",
     "incorrect_answers": ["Slovenia", "Switzerland", "Slovakia"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Blinky, Pinky, Inky and Clyde are characters from which classic video game?",
     "correct_answer": "Pac-Man", "incorrect_answers": ["Gauntlet", "Space Invaders", "Street Fighter"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What alcoholic drink is made from molasses?", "correct_answer": "Rum",
     "incorrect_answers": ["Gin", "Vodka", "Whisky"]}, {"category": "History", "type": "multiple", "difficulty": "easy",
                                                        "question": "Which of the following African countries was most successful in resisting colonization?",
                                                        "correct_answer": "Ethiopia",
                                                        "incorrect_answers": ["C&ocirc;te d&rsquo;Ivoire", "Congo",
                                                                              "Namibia"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "The series of the Intel HD graphics generation succeeding that of the 5000 and 6000 series (Broadwell) is called:",
     "correct_answer": "HD Graphics 500",
     "incorrect_answers": ["HD Graphics 700 ", "HD Graphics 600", "HD Graphics 7000"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "&quot;Tomb Raider&quot; icon Lara Croft was originally called...", "correct_answer": "Laura Cruz",
     "incorrect_answers": ["Laura Craft", "Laura Croft", "Lara Craft"]},
    {"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
     "question": "Which of these characters in &quot;Stranger Things&quot; has the power of Telekinesis?",
     "correct_answer": "Eleven", "incorrect_answers": ["Mike", "Lucas", "Karen"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What company created and developed the game &quot;Overwatch&quot;?",
     "correct_answer": "Blizzard Entertainment", "incorrect_answers": ["Valve", "Hi-Rez Studios", "Gearbox Software"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What is the first weapon you acquire in Half-Life?", "correct_answer": "A crowbar",
     "incorrect_answers": ["A pistol", "The H.E.V suit", "Your fists"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "Which Beatles album does NOT feature any of the band members on it&#039;s cover?",
     "correct_answer": "The Beatles (White Album)",
     "incorrect_answers": ["Rubber Soul", "Abbey Road", "Magical Mystery Tour"]},
    {"category": "Mythology", "type": "multiple", "difficulty": "easy",
     "question": "The greek god Poseidon was the god of what?", "correct_answer": "The Sea",
     "incorrect_answers": ["War", "Sun", "Fire"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "In &quot;Hexadecimal&quot;, what color would be displayed from the color code? &quot;#00FF00&quot;?",
     "correct_answer": "Green", "incorrect_answers": ["Red", "Blue", "Yellow"]},
    {"category": "History", "type": "multiple", "difficulty": "easy",
     "question": "What was the first sport to have been played on the moon?", "correct_answer": "Golf",
     "incorrect_answers": ["Football", "Tennis", "Soccer"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "Which 80s band is fronted by singer\/guitarist Robert Smith?", "correct_answer": "The Cure",
     "incorrect_answers": ["The Smiths", "Echo &amp; the Bunnymen", "New Order"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "Which team won 2014 FIFA World Cup in Brazil?", "correct_answer": "Germany",
     "incorrect_answers": ["Argentina", "Brazil", "Netherlands"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
     "question": "In the 1995 film &quot;Balto&quot;, who are Steele&#039;s accomplices?",
     "correct_answer": "Kaltag, Nikki, and Star",
     "incorrect_answers": ["Dusty, Kirby, and Ralph", "Nuk, Yak, and Sumac", "Jenna, Sylvie, and Dixie"]},
    {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
     "question": "The LS3 engine is how many cubic inches?", "correct_answer": "376",
     "incorrect_answers": ["346", "364", "427"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Who created the indie adventure game &quot;Night in the Woods&quot;?",
     "correct_answer": "Alec Holowka", "incorrect_answers": ["Ron Gilbert", "Tim Schafer", " Tommy Refenes"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In which year was League of Legends released?", "correct_answer": "2009",
     "incorrect_answers": ["2010", "2003", "2001"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "easy",
     "question": "In 2013, virtual pop-star Hatsune Miku had a sponsorship with which pizza chain?",
     "correct_answer": "Domino&#039;s", "incorrect_answers": ["Papa John&#039;s", "Pizza Hut", "Sabarro&#039;s"]},
    {"category": "History", "type": "multiple", "difficulty": "easy",
     "question": "What is the historical name of Sri Lanka?", "correct_answer": "Ceylon",
     "incorrect_answers": ["Myanmar", "Colombo", "Badulla"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
     "question": "In which film does Humphrey Bogart say the famous line, &quot;Here&#039;s looking at you, kid&quot;?",
     "correct_answer": "Casablanca",
     "incorrect_answers": ["The Maltese Falcon", "The Treasure of the Sierra Madre", "Citizen Kane"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What zodiac sign is represented by a pair of scales?", "correct_answer": "Libra",
     "incorrect_answers": ["Aries", "Capricorn", "Sagittarius"]},
    {"category": "Entertainment: Board Games", "type": "multiple", "difficulty": "easy",
     "question": "What is the maximum level you can have in a single class in Dungeons and Dragons (5e)?",
     "correct_answer": "20", "incorrect_answers": ["30", "15", "25"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "easy",
     "question": "Who is the main heroine of the anime, Full Metal Panic!", "correct_answer": "Kaname Chidori",
     "incorrect_answers": ["Teletha Testarossa", "Melissa Mao", "Kyoko Tokiwa"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following is an album by punk rock band Anti-Flag?",
     "correct_answer": "For Blood And Empire",
     "incorrect_answers": ["Infinity On High", "21st Century Breakdown", "No Pads, No Helmets...Just Balls"]}
]

question_data_tf = [
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The Great Wall of China is visible from the moon.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Gumbo is a stew that originated in Louisiana.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                       "question": "French is an official language in Canada.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The Sun rises from the North.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The color orange is named after the fruit.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                       "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                       "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Scotland voted to become an independent country during the referendum from September 2014.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The National Animal of Scotland is the Unicorn.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                       "question": "Slovakia is a member of European Union-", "correct_answer": "True",
                                       "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The mitochondria is the powerhouse of the cell.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
     "question": "Snakes and Ladders was originally created in India?", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The song &quot;Megalovania&quot; by Toby Fox made its third appearence in the 2015 RPG &quot;Undertale&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Musicals & Theatres", "type": "boolean", "difficulty": "easy",
     "question": "In the play Oedipus Rex, Oedipus kills his father due to jealousy in loving his mother.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "Eurobeat is primarily an Italian genre of music.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Animals", "type": "boolean", "difficulty": "easy",
                                       "question": "Kangaroos keep food in their pouches next to their children.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
     "question": "A universal set, or a set that contains all sets, exists.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                      "question": "Alaska is the largest state in the United States.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "RAM stands for Random Access Memory.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "The color orange is named after the fruit.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "easy",
     "question": "Deadpool&#039;s identity is Slade Wilson.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
     "question": "The Angry Video Game Nerd&#039;s alter ego is &quot;Board James&quot;.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                      "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
                                       "question": "In &quot;Star Trek&quot;, Klingons are aliens.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "New Haven is the capital city of the state of Connecticut in the United States.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The National Animal of Scotland is the Unicorn.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "History", "type": "boolean", "difficulty": "easy",
                                       "question": "The United States of America was the first country to launch a man into space.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
     "question": "An isosceles triangle has two sides of equal length as opposed to three.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                       "question": "A pasodoble is a type of Italian pasta sauce.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.", "correct_answer": "True",
     "incorrect_answers": ["False"]}]
